/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMeSection: typeof import('./src/components/AboutMeSection.vue')['default']
    ActivityCard: typeof import('./src/components/projects/lextrack/ActivityCard.vue')['default']
    AddMeeting: typeof import('./src/components/projects/lextrack/AddMeeting.vue')['default']
    ApiPlaygroundApp: typeof import('./src/components/projects/api-playground/ApiPlaygroundApp.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CustomNavBar: typeof import('./src/components/CustomNavBar.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Editor: typeof import('primevue/editor')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    GiftExchange: typeof import('./src/components/projects/gift-exchange/GiftExchange.vue')['default']
    GiftExchangeDraw: typeof import('./src/components/projects/gift-exchange/GiftExchangeDraw.vue')['default']
    GiftExchangeJoin: typeof import('./src/components/projects/gift-exchange/GiftExchangeJoin.vue')['default']
    GiftExchangeManage: typeof import('./src/components/projects/gift-exchange/GiftExchangeManage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LargaApp: typeof import('./src/components/projects/larga/LargaApp.vue')['default']
    LexTrackApp: typeof import('./src/components/projects/lextrack/LexTrackApp.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    ManageMeeting: typeof import('./src/components/projects/lextrack/ManageMeeting.vue')['default']
    ManageSupport: typeof import('./src/components/projects/lextrack/ManageSupport.vue')['default']
    ManageTask: typeof import('./src/components/projects/lextrack/ManageTask.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('primevue/tag')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
